In [16]:
import pandas as pd 
import numpy as np

# Dataset load

In [17]:
df = pd.read_csv("C:/Users/HP/Downloads/E-commerce_Delivery_Shipping_Data_2026.csv")

# Dataset Copy

In [18]:
df_copy = df.copy()

In [19]:
df_copy.head()

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
0,ORD-000001,2026-11-15,CUS-002353,Small Business,Tokyo,Japan,WH-004,Toronto,Home & Kitchen,8.23,...,Large,Digital Wallet,Normal,Snow,3,Yes,Late Delivery,2,25.1,Delivered
1,ORD-000002,2026-04-08,CUS-003258,Consumer,Vancouver,Canada,WH-007,Paris,Beauty,0.10,...,Small,Debit Card,Normal,Cloudy,5,No,NaN,1,25.9,Delivered
2,ORD-000003,2026-01-05,CUS-001221,Consumer,Houston,United States,WH-005,London,Home & Kitchen,5.51,...,Large,Debit Card,Low,Snow,4,Yes,Product Defect,1,31.5,Delivered
3,ORD-000004,2026-05-29,CUS-001717,Small Business,Delhi,India,WH-002,Los Angeles,Grocery,3.75,...,Large,Debit Card,Normal,Snow,3,No,NaN,1,12.6,In Transit
4,ORD-000005,2026-02-22,CUS-000716,Small Business,Nagoya,Japan,WH-006,Berlin,Beauty,0.10,...,Small,Credit Card,Normal,Storm,2,No,NaN,1,24.9,Delivered

In [20]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    50000 non-null  object
 1   order_date                  50000 non-null  object
 2   customer_id                 50000 non-null  object
 3   customer_segment            50000 non-null  object
 4   customer_city               50000 non-null  object
 5   customer_country            50000 non-null  object
 6   warehouse_id                50000 non-null  object
 7   warehouse_city              50000 non-null  object
 8   product_category            50000 non-null  object
 9   product_weight_kg           50000 non-null  float64
 10  order_value_usd             50000 non-null  float64
 11  shipping_method             50000 non-null  object
 12  carrier                     50000 non-null  object
 13  distance_km                 50000 non-null  float64
 14  promised_delivery_days      50000 non-null  int64
 15  actual_delivery_days        50000 non-null  int64
 16  delivery_status             50000 non-null  object
 17  late_delivery               50000 non-null  object
 18  delivery_delay_days         50000 non-null  int64
 19  shipping_cost_usd           50000 non-null  float64
 20  package_size                50000 non-null  object
 21  payment_method              50000 non-null  object
 22  order_priority              50000 non-null  object
 23  weather_condition           50000 non-null  object
 24  customer_rating             50000 non-null  int64
 25  return_requested            50000 non-null  object
 26  return_reason               8625 non-null   object
 27  delivery_attempts           50000 non-null  int64
 28  warehouse_processing_hours  50000 non-null  float64
 29  tracking_status             50000 non-null  object
dtypes: float64(5), int64(5), object(20)
memory usage: 11.4+ MB

In [21]:
df_copy.describe()

,product_weight_kg,order_value_usd,distance_km,promised_delivery_days,actual_delivery_days,delivery_delay_days,shipping_cost_usd,customer_rating,delivery_attempts,warehouse_processing_hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,2.255028,177.917107,2496.778802,7.197700,8.345940,1.281080,120.515538,3.371840,1.169860,14.412430
std,3.694952,291.600047,1774.633152,3.680229,4.644353,1.679527,108.680030,0.998777,0.390756,9.924904
min,0.100000,10.000000,40.000000,0.000000,0.000000,0.000000,4.050000,1.000000,1.000000,1.000000
25%,0.320000,28.720000,1086.775000,4.000000,5.000000,0.000000,40.640000,3.000000,1.000000,6.600000
50%,0.930000,76.840000,2182.800000,6.000000,8.000000,1.000000,82.970000,3.000000,1.000000,11.900000
75%,2.610000,173.162500,3592.475000,11.000000,12.000000,2.000000,167.422500,4.000000,1.000000,20.700000
max,52.190000,3530.730000,9553.600000,15.000000,27.000000,13.000000,500.000000,5.000000,3.000000,48.000000

# Duplicates Check

In [22]:
df_copy.duplicated().sum()

np.int64(0)

# Missing Values Cheak and Handling

In [23]:
df_copy.isnull().sum()

order_id                          0
order_date                        0
customer_id                       0
customer_segment                  0
customer_city                     0
customer_country                  0
warehouse_id                      0
warehouse_city                    0
product_category                  0
product_weight_kg                 0
order_value_usd                   0
shipping_method                   0
carrier                           0
distance_km                       0
promised_delivery_days            0
actual_delivery_days              0
delivery_status                   0
late_delivery                     0
delivery_delay_days               0
shipping_cost_usd                 0
package_size                      0
payment_method                    0
order_priority                    0
weather_condition                 0
customer_rating                   0
return_requested                  0
return_reason                 41375
delivery_attempts                 0
warehouse_processing_hours        0
tracking_status                   0
dtype: int64

In [24]:
df_copy['return_reason'] = df_copy['return_reason'].fillna("Not mentioned")

In [25]:
df_copy.isnull().sum()

order_id                      0
order_date                    0
customer_id                   0
customer_segment              0
customer_city                 0
customer_country              0
warehouse_id                  0
warehouse_city                0
product_category              0
product_weight_kg             0
order_value_usd               0
shipping_method               0
carrier                       0
distance_km                   0
promised_delivery_days        0
actual_delivery_days          0
delivery_status               0
late_delivery                 0
delivery_delay_days           0
shipping_cost_usd             0
package_size                  0
payment_method                0
order_priority                0
weather_condition             0
customer_rating               0
return_requested              0
return_reason                 0
delivery_attempts             0
warehouse_processing_hours    0
tracking_status               0
dtype: int64

In [26]:
print("Original rows:", 50000)
print("Current rows:", df_copy.shape[0])

Original rows: 50000
Current rows: 50000

# Data type check

In [27]:
df_copy.dtypes

order_id                       object
order_date                     object
customer_id                    object
customer_segment               object
customer_city                  object
customer_country               object
warehouse_id                   object
warehouse_city                 object
product_category               object
product_weight_kg             float64
order_value_usd               float64
shipping_method                object
carrier                        object
distance_km                   float64
promised_delivery_days          int64
actual_delivery_days            int64
delivery_status                object
late_delivery                  object
delivery_delay_days             int64
shipping_cost_usd             float64
package_size                   object
payment_method                 object
order_priority                 object
weather_condition              object
customer_rating                 int64
return_requested               object
return_reason                  object
delivery_attempts               int64
warehouse_processing_hours    float64
tracking_status                object
dtype: object

# Data type Cleaning

In [28]:
# The order_date column is currently stored as an object data type. 
#Converting it into a proper datetime format allows accurate date-based analysis.

df_copy["order_date"] = pd.to_datetime(
    df_copy["order_date"],
    errors="coerce"
)

print("Order Date Data Type:", df_copy["order_date"].dtype)

Order Date Data Type: datetime64[ns]

In [29]:

print("Invalid dates:", df_copy["order_date"].isna().sum())

Invalid dates: 0

In [30]:
df_copy.dtypes

order_id                              object
order_date                    datetime64[ns]
customer_id                           object
customer_segment                      object
customer_city                         object
customer_country                      object
warehouse_id                          object
warehouse_city                        object
product_category                      object
product_weight_kg                    float64
order_value_usd                      float64
shipping_method                       object
carrier                               object
distance_km                          float64
promised_delivery_days                 int64
actual_delivery_days                   int64
delivery_status                       object
late_delivery                         object
delivery_delay_days                    int64
shipping_cost_usd                    float64
package_size                          object
payment_method                        object
order_priority                        object
weather_condition                     object
customer_rating                        int64
return_requested                      object
return_reason                         object
delivery_attempts                      int64
warehouse_processing_hours           float64
tracking_status                       object
dtype: object

# Outlier Detection

In [31]:
numerical_columns = [
    "product_weight_kg",
    "order_value_usd",
    "distance_km",
    "promised_delivery_days",
    "actual_delivery_days",
    "delivery_delay_days",
    "shipping_cost_usd",
    "customer_rating",
    "delivery_attempts",
    "warehouse_processing_hours"
]

display(df_copy[numerical_columns].describe())

,product_weight_kg,order_value_usd,distance_km,promised_delivery_days,actual_delivery_days,delivery_delay_days,shipping_cost_usd,customer_rating,delivery_attempts,warehouse_processing_hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,2.255028,177.917107,2496.778802,7.197700,8.345940,1.281080,120.515538,3.371840,1.169860,14.412430
std,3.694952,291.600047,1774.633152,3.680229,4.644353,1.679527,108.680030,0.998777,0.390756,9.924904
min,0.100000,10.000000,40.000000,0.000000,0.000000,0.000000,4.050000,1.000000,1.000000,1.000000
25%,0.320000,28.720000,1086.775000,4.000000,5.000000,0.000000,40.640000,3.000000,1.000000,6.600000
50%,0.930000,76.840000,2182.800000,6.000000,8.000000,1.000000,82.970000,3.000000,1.000000,11.900000
75%,2.610000,173.162500,3592.475000,11.000000,12.000000,2.000000,167.422500,4.000000,1.000000,20.700000
max,52.190000,3530.730000,9553.600000,15.000000,27.000000,13.000000,500.000000,5.000000,3.000000,48.000000

In [32]:
# Define numerical columns for outlier detection
numerical_columns = [
    "product_weight_kg",
    "order_value_usd",
    "distance_km",
    "promised_delivery_days",
    "actual_delivery_days",
    "delivery_delay_days",
    "shipping_cost_usd",
    "customer_rating",
    "delivery_attempts",
    "warehouse_processing_hours"
]

# Calculate outliers using IQR
outlier_summary = []

for column in numerical_columns:
    Q1 = df_copy[column].quantile(0.25)
    Q3 = df_copy[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df_copy[
        (df_copy[column] < lower_limit) |
        (df_copy[column] > upper_limit)
    ]

    outlier_summary.append({
        "Column": column,
        "Lower Limit": round(lower_limit, 2),
        "Upper Limit": round(upper_limit, 2),
        "Outlier Count": len(outliers)
    })

outlier_df_copy = pd.DataFrame(outlier_summary)

display(outlier_df_copy)

                       Column  Lower Limit  Upper Limit  Outlier Count
0           product_weight_kg        -3.12         6.04           4712
1             order_value_usd      -187.94       389.83           5926
2                 distance_km     -2671.77      7351.02            656
3      promised_delivery_days        -6.50        21.50              0
4        actual_delivery_days        -5.50        22.50             61
5         delivery_delay_days        -3.00         5.00           1638
6           shipping_cost_usd      -149.53       357.60           2416
7             customer_rating         1.50         5.50            962
8           delivery_attempts         1.00         1.00           8201
9  warehouse_processing_hours       -14.55        41.85           1044

# Outlier Treatment
Purpose:
Instead of deleting valid logistics records, extreme values will be capped at the calculated IQR lower and upper limits. This reduces the influence of extreme observations while preserving the original records.

In [33]:
outlier_columns = [
    "product_weight_kg",
    "order_value_usd",
    "distance_km",
    "actual_delivery_days",
    "delivery_delay_days",
    "shipping_cost_usd",
    "warehouse_processing_hours"
]

for column in outlier_columns:
    Q1 = df_copy[column].quantile(0.25)
    Q3 = df_copy[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    df_copy[column] = df_copy[column].clip(
        lower=lower_limit,
        upper=upper_limit
    )

print("Outlier treatment completed successfully.")

Outlier treatment completed successfully.

In [34]:
display(df_copy[outlier_columns].describe())

,product_weight_kg,order_value_usd,distance_km,actual_delivery_days,delivery_delay_days,shipping_cost_usd,warehouse_processing_hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,1.766319,125.057213,2487.004534,8.344310,1.214320,116.670983,14.347858
std,1.933629,124.647052,1744.552506,4.639022,1.460544,97.681480,9.730795
min,0.100000,10.000000,40.000000,0.000000,0.000000,4.050000,1.000000
25%,0.320000,28.720000,1086.775000,5.000000,0.000000,40.640000,6.600000
50%,0.930000,76.840000,2182.800000,8.000000,1.000000,82.970000,11.900000
75%,2.610000,173.162500,3592.475000,12.000000,2.000000,167.422500,20.700000
max,6.045000,389.826250,7351.025000,22.500000,5.000000,357.596250,41.850000

# Categorical Data Encoding

In [35]:
categorical_columns = df_copy.select_dtypes(
    include="object"
).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
['order_id', 'customer_id', 'customer_segment', 'customer_city', 'customer_country', 'warehouse_id', 'warehouse_city', 'product_category', 'shipping_method', 'carrier', 'delivery_status', 'late_delivery', 'package_size', 'payment_method', 'order_priority', 'weather_condition', 'return_requested', 'return_reason', 'tracking_status']

In [36]:
encoding_columns = [
    "customer_segment",
    "product_category",
    "shipping_method",
    "delivery_status",
    "late_delivery",
    "package_size",
    "payment_method",
    "order_priority",
    "weather_condition",
    "return_requested",
    "tracking_status"
]

print("Columns selected for encoding:")
print(encoding_columns)

Columns selected for encoding:
['customer_segment', 'product_category', 'shipping_method', 'delivery_status', 'late_delivery', 'package_size', 'payment_method', 'order_priority', 'weather_condition', 'return_requested', 'tracking_status']

In [37]:
for column in encoding_columns:
    print(f"\n{column}:")
    print(df_copy[column].value_counts())

customer_segment:
customer_segment
Consumer          30167
Small Business     9947
Enterprise         6027
Premium            3859
Name: count, dtype: int64

product_category:
product_category
Electronics               7406
Fashion                   7158
Home & Kitchen            5902
Grocery                   4054
Beauty                    3976
Books                     3598
Sports & Fitness          3466
Health & Personal Care    3061
Toys                      3050
Office Supplies           2953
Automotive                2908
Pet Supplies              2468
Name: count, dtype: int64

shipping_method:
shipping_method
Standard         17027
International    15839
Express           9696
Economy           5577
Same Day          1861
Name: count, dtype: int64

delivery_status:
delivery_status
Delivered          44184
In Transit          4007
Delayed             1806
Failed Delivery        3
Name: count, dtype: int64

late_delivery:
late_delivery
Yes    28162
No     21838
Name: count, dtype: int64

package_size:
package_size
Medium       18648
Small        14560
Large        13615
Oversized     3177
Name: count, dtype: int64

payment_method:
payment_method
Credit Card         15032
Debit Card          12431
PayPal               9016
Digital Wallet       6061
Bank Transfer        3952
Cash on Delivery     3508
Name: count, dtype: int64

order_priority:
order_priority
Normal    22450
High      15175
Low        7455
Urgent     4920
Name: count, dtype: int64

weather_condition:
weather_condition
Clear           14932
Cloudy          12582
Rain             9142
Storm            4991
Snow             4913
Extreme Heat     3440
Name: count, dtype: int64

return_requested:
return_requested
No     41375
Yes     8625
Name: count, dtype: int64

tracking_status:
tracking_status
Delivered           44184
In Transit           4894
Exception             921
Out for Delivery        1
Name: count, dtype: int64

# One-Hot Encoding

In [38]:
df_copy = pd.get_dummies(
    df_copy,
    columns=encoding_columns,
    drop_first=True,
    dtype=int
)

print("One-hot encoding completed successfully.")
print("New dataset shape:", df_copy.shape)

One-hot encoding completed successfully.
New dataset shape: (50000, 61)

In [39]:
print("Updated Dataset Columns:")
print(df_copy.columns.tolist())

Updated Dataset Columns:
['order_id', 'order_date', 'customer_id', 'customer_city', 'customer_country', 'warehouse_id', 'warehouse_city', 'product_weight_kg', 'order_value_usd', 'carrier', 'distance_km', 'promised_delivery_days', 'actual_delivery_days', 'delivery_delay_days', 'shipping_cost_usd', 'customer_rating', 'return_reason', 'delivery_attempts', 'warehouse_processing_hours', 'customer_segment_Enterprise', 'customer_segment_Premium', 'customer_segment_Small Business', 'product_category_Beauty', 'product_category_Books', 'product_category_Electronics', 'product_category_Fashion', 'product_category_Grocery', 'product_category_Health & Personal Care', 'product_category_Home & Kitchen', 'product_category_Office Supplies', 'product_category_Pet Supplies', 'product_category_Sports & Fitness', 'product_category_Toys', 'shipping_method_Express', 'shipping_method_International', 'shipping_method_Same Day', 'shipping_method_Standard', 'delivery_status_Delivered', 'delivery_status_Failed Delivery', 'delivery_status_In Transit', 'late_delivery_Yes', 'package_size_Medium', 'package_size_Oversized', 'package_size_Small', 'payment_method_Cash on Delivery', 'payment_method_Credit Card', 'payment_method_Debit Card', 'payment_method_Digital Wallet', 'payment_method_PayPal', 'order_priority_Low', 'order_priority_Normal', 'order_priority_Urgent', 'weather_condition_Cloudy', 'weather_condition_Extreme Heat', 'weather_condition_Rain', 'weather_condition_Snow', 'weather_condition_Storm', 'return_requested_Yes', 'tracking_status_Exception', 'tracking_status_In Transit', 'tracking_status_Out for Delivery']

In [40]:
df_copy.head()

,order_id,order_date,customer_id,customer_city,customer_country,warehouse_id,warehouse_city,product_weight_kg,order_value_usd,carrier,...,order_priority_Urgent,weather_condition_Cloudy,weather_condition_Extreme Heat,weather_condition_Rain,weather_condition_Snow,weather_condition_Storm,return_requested_Yes,tracking_status_Exception,tracking_status_In Transit,tracking_status_Out for Delivery
0,ORD-000001,2026-11-15,CUS-002353,Tokyo,Japan,WH-004,Toronto,6.045,10.39,EagleCourier,...,0,0,0,0,1,0,1,0,0,0
1,ORD-000002,2026-04-08,CUS-003258,Vancouver,Canada,WH-007,Paris,0.100,117.69,BlueRoute,...,0,1,0,0,0,0,0,0,0,0
2,ORD-000003,2026-01-05,CUS-001221,Houston,United States,WH-005,London,5.510,335.23,SpeedyCargo,...,0,0,0,0,1,0,1,0,0,0
3,ORD-000004,2026-05-29,CUS-001717,Delhi,India,WH-002,Los Angeles,3.750,10.57,ParcelPro,...,0,0,0,0,1,0,0,0,1,0
4,ORD-000005,2026-02-22,CUS-000716,Nagoya,Japan,WH-006,Berlin,0.100,31.37,GlobalExpress,...,0,0,0,0,0,1,0,0,0,0

# Final Data Quality cheak

In [41]:
print("Final Dataset Shape:", df_copy.shape)

print("\nTotal Missing Values:")
print(df_copy.isnull().sum().sum())

print("\nTotal Duplicate Records:")
print(df_copy.duplicated().sum())

print("\nData Types:")
print(df_copy.dtypes.value_counts())

Final Dataset Shape: (50000, 61)

Total Missing Values:
0

Total Duplicate Records:
0

Data Types:
int64             46
object             8
float64            6
datetime64[ns]     1
Name: count, dtype: int64

In [42]:
df_copy.head()

,order_id,order_date,customer_id,customer_city,customer_country,warehouse_id,warehouse_city,product_weight_kg,order_value_usd,carrier,...,order_priority_Urgent,weather_condition_Cloudy,weather_condition_Extreme Heat,weather_condition_Rain,weather_condition_Snow,weather_condition_Storm,return_requested_Yes,tracking_status_Exception,tracking_status_In Transit,tracking_status_Out for Delivery
0,ORD-000001,2026-11-15,CUS-002353,Tokyo,Japan,WH-004,Toronto,6.045,10.39,EagleCourier,...,0,0,0,0,1,0,1,0,0,0
1,ORD-000002,2026-04-08,CUS-003258,Vancouver,Canada,WH-007,Paris,0.100,117.69,BlueRoute,...,0,1,0,0,0,0,0,0,0,0
2,ORD-000003,2026-01-05,CUS-001221,Houston,United States,WH-005,London,5.510,335.23,SpeedyCargo,...,0,0,0,0,1,0,1,0,0,0
3,ORD-000004,2026-05-29,CUS-001717,Delhi,India,WH-002,Los Angeles,3.750,10.57,ParcelPro,...,0,0,0,0,1,0,0,0,1,0
4,ORD-000005,2026-02-22,CUS-000716,Nagoya,Japan,WH-006,Berlin,0.100,31.37,GlobalExpress,...,0,0,0,0,0,1,0,0,0,0

In [43]:
df_copy.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_city',
       'customer_country', 'warehouse_id', 'warehouse_city',
       'product_weight_kg', 'order_value_usd', 'carrier', 'distance_km',
       'promised_delivery_days', 'actual_delivery_days', 'delivery_delay_days',
       'shipping_cost_usd', 'customer_rating', 'return_reason',
       'delivery_attempts', 'warehouse_processing_hours',
       'customer_segment_Enterprise', 'customer_segment_Premium',
       'customer_segment_Small Business', 'product_category_Beauty',
       'product_category_Books', 'product_category_Electronics',
       'product_category_Fashion', 'product_category_Grocery',
       'product_category_Health & Personal Care',
       'product_category_Home & Kitchen', 'product_category_Office Supplies',
       'product_category_Pet Supplies', 'product_category_Sports & Fitness',
       'product_category_Toys', 'shipping_method_Express',
       'shipping_method_International', 'shipping_method_Same Day',
       'shipping_method_Standard', 'delivery_status_Delivered',
       'delivery_status_Failed Delivery', 'delivery_status_In Transit',
       'late_delivery_Yes', 'package_size_Medium', 'package_size_Oversized',
       'package_size_Small', 'payment_method_Cash on Delivery',
       'payment_method_Credit Card', 'payment_method_Debit Card',
       'payment_method_Digital Wallet', 'payment_method_PayPal',
       'order_priority_Low', 'order_priority_Normal', 'order_priority_Urgent',
       'weather_condition_Cloudy', 'weather_condition_Extreme Heat',
       'weather_condition_Rain', 'weather_condition_Snow',
       'weather_condition_Storm', 'return_requested_Yes',
       'tracking_status_Exception', 'tracking_status_In Transit',
       'tracking_status_Out for Delivery'],
      dtype='object')

# Normalization/Standardization add

## 8. Data Normalization / Standardization

Normalization is performed to bring numerical features to a comparable scale.
StandardScaler is used to standardize numerical variables by removing the mean
and scaling them to unit variance.

This is useful because logistics features such as distance, shipping cost,
delivery days, and order value have different numerical ranges.

In [44]:
from sklearn.preprocessing import StandardScaler

# Numerical columns selected for standardization
scaling_columns = [
    "distance_km",
    "shipping_cost_usd",
    "actual_delivery_days",
    "delivery_delay_days"
]

# Create scaler
scaler = StandardScaler()

# Apply standardization
df_copy[scaling_columns] = scaler.fit_transform(
    df_copy[scaling_columns]
)

print("Standardization completed successfully.")

Standardization completed successfully.

In [45]:
df_copy[scaling_columns].describe()

,distance_km,shipping_cost_usd,actual_delivery_days,delivery_delay_days
count,5.000000e+04,5.000000e+04,5.000000e+04,5.000000e+04
mean,-8.185452e-17,-9.890755e-17,-2.728484e-17,4.263256e-18
std,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00
min,-1.402669e+00,-1.152953e+00,-1.798740e+00,-8.314244e-01
25%,-8.026377e-01,-7.783640e-01,-7.209156e-01,-8.314244e-01
50%,-1.743757e-01,-3.450124e-01,-7.422113e-02,-1.467413e-01
75%,6.336763e-01,5.195665e-01,7.880382e-01,5.379418e-01
max,2.788147e+00,2.466462e+00,3.051469e+00,2.591991e+00

## 9. Final Data Quality Check

After completing the preprocessing steps, the dataset is checked again
for missing values, duplicate records, and data types. This ensures that
the final dataset is suitable for further analysis and machine learning.

In [46]:
print("Final Dataset Shape:", df_copy.shape)

print("\nTotal Missing Values:")
print(df_copy.isnull().sum().sum())

print("\nTotal Duplicate Rows:")
print(df_copy.duplicated().sum())

print("\nData Types:")
print(df_copy.dtypes)

Final Dataset Shape: (50000, 61)

Total Missing Values:
0

Total Duplicate Rows:
0

Data Types:
order_id                                    object
order_date                          datetime64[ns]
customer_id                                 object
customer_city                               object
customer_country                            object
                                         ...
weather_condition_Storm                      int64
return_requested_Yes                         int64
tracking_status_Exception                    int64
tracking_status_In Transit                   int64
tracking_status_Out for Delivery             int64
Length: 61, dtype: object

In [47]:
missing = df_copy.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Series([], dtype: int64)

In [48]:
print(df_copy["return_reason"].dtype)

object

In [54]:
print(df_copy["return_reason"].isnull().sum())

0

# Befor and After Dataset

In [51]:
print("Original Dataset Shape:", df.shape)
print("Preprocessed Dataset Shape:", df_copy.shape)

Original Dataset Shape: (50000, 30)
Preprocessed Dataset Shape: (50000, 61)

In [53]:
for col in scaling_columns:
    print(f"\n{col}")
    print("Minimum:", df_copy[col].min())
    print("Maximum:", df_copy[col].max())

distance_km
Minimum: -1.402668590248024
Maximum: 2.7881471550970804

shipping_cost_usd
Minimum: -1.1529525303387864
Maximum: 2.4664621885798814

actual_delivery_days
Minimum: -1.798739748677793
Maximum: 3.051468877949255

delivery_delay_days
Minimum: -0.8314243928522556
Maximum: 2.5919911518651815


## Reflection and Impact of Data Quality

Data quality has a significant impact on logistics analytics and decision-making.
Missing values can reduce the reliability of analysis, while duplicate records
can lead to incorrect business results. Outliers may distort statistical
analysis and machine learning models. Therefore, missing values were handled,
duplicate records were identified, outliers were treated using the IQR method,
categorical variables were encoded, and numerical variables were standardized.

After preprocessing, the dataset becomes more consistent and suitable for
further analysis. A clean dataset can help logistics organizations analyze
delivery performance, shipping costs, transportation distance, delays, and
customer-related patterns more accurately. High-quality data also improves
the reliability of predictive models and supports better operational
decision-making.

## Conclusion

The Week 2 data preprocessing pipeline successfully prepared the e-commerce
logistics dataset for further analysis. The process included data collection,
data inspection, duplicate detection, missing-value handling, date conversion,
outlier treatment, categorical encoding, and numerical standardization.

The cleaned and preprocessed dataset can now be used for exploratory data
analysis, visualization, regression, clustering, and other machine learning
tasks in logistics.